# Generated by Django 5.0 on 2024-02-22 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oddeleni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='Oddeleni',
            field=models.ManyToManyField(blank=True, related_name='pokoje', to='oddeleni.pokoje'),
        ),
        migrations.AlterField(
            model_name='pokoje',
            name='Pokoj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacienti', to='oddeleni.oddeleni'),
        ),
    ]
